import { TemplateTaskData, WorkflowPhaseTemplateData } from '../project-template.service';

export const PREDEFINED_TEMPLATES: Record<string, TemplateTaskData[]> = {
  // هيئة كهرباء ومياه - FEWA
  FEWA: [
    {
      name: 'Prepare FEWA Application Documents',
      nameAr: 'إعداد مستندات طلب هيئة الكهرباء',
      slaDays: 3,
      order: 1,
      estimatedMinutes: 480,
      color: '#3B82F6',
    },
    {
      name: 'Submit Application to FEWA',
      nameAr: 'تقديم الطلب لهيئة الكهرباء',
      slaDays: 7,
      order: 2,
      dependencies: [1],
      governmentEntity: 'FEWA - Federal Electricity & Water Authority',
      governmentEntityAr: 'هيئة الكهرباء والماء',
      color: '#3B82F6',
    },
    {
      name: 'FEWA Technical Review',
      nameAr: 'المراجعة الفنية لهيئة الكهرباء',
      slaDays: 14,
      order: 3,
      dependencies: [2],
      governmentEntity: 'FEWA - Federal Electricity & Water Authority',
      governmentEntityAr: 'هيئة الكهرباء والماء',
      color: '#3B82F6',
    },
    {
      name: 'FEWA Site Inspection',
      nameAr: 'معاينة الموقع من هيئة الكهرباء',
      slaDays: 7,
      order: 4,
      dependencies: [3],
      governmentEntity: 'FEWA - Federal Electricity & Water Authority',
      governmentEntityAr: 'هيئة الكهرباء والماء',
      color: '#3B82F6',
    },
    {
      name: 'Obtain FEWA Approval/Connection',
      nameAr: 'الحصول على موافقة/توصيل هيئة الكهرباء',
      slaDays: 7,
      order: 5,
      dependencies: [4],
      governmentEntity: 'FEWA - Federal Electricity & Water Authority',
      governmentEntityAr: 'هيئة الكهرباء والماء',
      color: '#10B981',
    },
  ],

  // الدفاع المدني - Civil Defense
  CIVIL_DEFENSE: [
    {
      name: 'Prepare Civil Defense Drawings',
      nameAr: 'إعداد رسومات الدفاع المدني',
      slaDays: 5,
      order: 1,
      estimatedMinutes: 960,
      color: '#EF4444',
    },
    {
      name: 'Submit to Civil Defense',
      nameAr: 'تقديم للدفاع المدني',
      slaDays: 7,
      order: 2,
      dependencies: [1],
      governmentEntity: 'Civil Defense',
      governmentEntityAr: 'الدفاع المدني',
      color: '#EF4444',
    },
    {
      name: 'Civil Defense Plan Review',
      nameAr: 'مراجعة المخطط من الدفاع المدني',
      slaDays: 14,
      order: 3,
      dependencies: [2],
      governmentEntity: 'Civil Defense',
      governmentEntityAr: 'الدفاع المدني',
      color: '#EF4444',
    },
    {
      name: 'Civil Defense Site Inspection',
      nameAr: 'معاينة الموقع من الدفاع المدني',
      slaDays: 7,
      order: 4,
      dependencies: [3],
      governmentEntity: 'Civil Defense',
      governmentEntityAr: 'الدفاع المدني',
      color: '#EF4444',
    },
    {
      name: 'Obtain Civil Defense Certificate',
      nameAr: 'الحصول على شهادة الدفاع المدني',
      slaDays: 5,
      order: 5,
      dependencies: [4],
      governmentEntity: 'Civil Defense',
      governmentEntityAr: 'الدفاع المدني',
      color: '#10B981',
    },
  ],

  // البلدية - Municipality
  MUNICIPALITY: [
    {
      name: 'Prepare Municipality Permit Documents',
      nameAr: 'إعداد مستندات تصريح البلدية',
      slaDays: 3,
      order: 1,
      estimatedMinutes: 720,
      color: '#8B5CF6',
    },
    {
      name: 'Submit Building Permit Application',
      nameAr: 'تقديم طلب ترخيص بناء',
      slaDays: 5,
      order: 2,
      dependencies: [1],
      governmentEntity: 'Municipality',
      governmentEntityAr: 'البلدية',
      color: '#8B5CF6',
    },
    {
      name: 'Municipality Technical Review',
      nameAr: 'المراجعة الفنية للبلدية',
      slaDays: 21,
      order: 3,
      dependencies: [2],
      governmentEntity: 'Municipality',
      governmentEntityAr: 'البلدية',
      color: '#8B5CF6',
    },
    {
      name: 'Municipality Committee Approval',
      nameAr: 'موافقة لجنة البلدية',
      slaDays: 14,
      order: 4,
      dependencies: [3],
      governmentEntity: 'Municipality',
      governmentEntityAr: 'البلدية',
      color: '#8B5CF6',
    },
    {
      name: 'Issue Building Permit',
      nameAr: 'إصدار رخصة البناء',
      slaDays: 7,
      order: 5,
      dependencies: [4],
      governmentEntity: 'Municipality',
      governmentEntityAr: 'البلدية',
      color: '#10B981',
    },
  ],

  // اتصالات - Etisalat/Telecom
  TELECOM: [
    {
      name: 'Prepare Telecom Connection Application',
      nameAr: 'إعداد طلب توصيل الاتصالات',
      slaDays: 2,
      order: 1,
      estimatedMinutes: 240,
      color: '#06B6D4',
    },
    {
      name: 'Submit to Telecom Provider',
      nameAr: 'تقديم لمزود الاتصالات',
      slaDays: 5,
      order: 2,
      dependencies: [1],
      governmentEntity: 'Etisalat/Du',
      governmentEntityAr: 'اتصالات/دو',
      color: '#06B6D4',
    },
    {
      name: 'Telecom Technical Survey',
      nameAr: 'المسح الفني للاتصالات',
      slaDays: 7,
      order: 3,
      dependencies: [2],
      governmentEntity: 'Etisalat/Du',
      governmentEntityAr: 'اتصالات/دو',
      color: '#06B6D4',
    },
    {
      name: 'Telecom Installation',
      nameAr: 'تركيب خطوط الاتصالات',
      slaDays: 14,
      order: 4,
      dependencies: [3],
      governmentEntity: 'Etisalat/Du',
      governmentEntityAr: 'اتصالات/دو',
      color: '#06B6D4',
    },
    {
      name: 'Telecom Connection Activation',
      nameAr: 'تفعيل خدمة الاتصالات',
      slaDays: 3,
      order: 5,
      dependencies: [4],
      governmentEntity: 'Etisalat/Du',
      governmentEntityAr: 'اتصالات/دو',
      color: '#10B981',
    },
  ],
};

// ============================================
// Architectural & Contract Workflow Phase Templates
// قوالب مراحل سير العمل المعمارية والعقود
// ============================================

export function createArchitecturalTemplate(): WorkflowPhaseTemplateData[] {
  return [
    {
      phaseType: 'ARCHITECTURAL_SKETCH',
      phaseTypeAr: 'التصميم التخطيطي',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Schematic design phase - initial architectural concept',
      descriptionAr: 'مرحلة التصميم التخطيطي - المفهوم المعماري الأولي',
      slaDays: 4,
      slaWarningDays: 3,
      order: 1,
      color: '#3B82F6',
    },
    {
      phaseType: 'CLIENT_APPROVAL',
      phaseTypeAr: 'اعتماد العميل للفكرة',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Client review and approval of concept design',
      descriptionAr: 'مراجعة العميل والموافقة على الفكرة التصميمية',
      slaDays: 3,
      slaWarningDays: 2,
      order: 2,
      dependsOnOrder: 1,
      color: '#F59E0B',
    },
    {
      phaseType: 'MODIFICATIONS',
      phaseTypeAr: 'تعديلات التصميم',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Design modifications based on client feedback',
      descriptionAr: 'تعديلات التصميم بناءً على ملاحظات العميل',
      slaDays: 4,
      slaWarningDays: 3,
      order: 3,
      dependsOnOrder: 2,
      color: '#EF4444',
    },
    {
      phaseType: 'LETTER_OF_INTENT',
      phaseTypeAr: 'خطاب النوايا',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Issue letter of intent for the project',
      descriptionAr: 'إصدار خطاب النوايا للمشروع',
      slaDays: 1,
      slaWarningDays: 1,
      order: 4,
      dependsOnOrder: 3,
      color: '#8B5CF6',
    },
    {
      phaseType: 'PRELIMINARY',
      phaseTypeAr: 'تطوير المخططات الأولية',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Development of preliminary drawings',
      descriptionAr: 'تطوير المخططات الأولية للمشروع',
      slaDays: 6,
      slaWarningDays: 4,
      order: 5,
      dependsOnOrder: 4,
      color: '#6366F1',
    },
    {
      phaseType: 'PRELIMINARY_APPROVAL',
      phaseTypeAr: 'اعتماد المخططات الأولية',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Client approval of preliminary drawings',
      descriptionAr: 'اعتماد العميل للمخططات الأولية',
      slaDays: 7,
      slaWarningDays: 5,
      order: 6,
      dependsOnOrder: 5,
      color: '#F59E0B',
    },
    {
      phaseType: 'DESIGN_CONTRACT',
      phaseTypeAr: 'توقيع عقد التصميم',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Sign the design contract with client',
      descriptionAr: 'توقيع عقد التصميم مع العميل',
      slaDays: 1,
      slaWarningDays: 1,
      order: 7,
      dependsOnOrder: 6,
      color: '#10B981',
    },
    {
      phaseType: 'GREEN_BUILDING_CHECK',
      phaseTypeAr: 'قائمة التحقق الخضراء',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Green building checklist compliance review',
      descriptionAr: 'قائمة التحقق من متطلبات المباني الخضراء',
      slaDays: 1,
      slaWarningDays: 1,
      order: 8,
      dependsOnOrder: 7,
      color: '#22C55E',
    },
    {
      phaseType: 'THREE_D_MAX',
      phaseTypeAr: 'التصميم الخارجي 3D',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Exterior 3D visualization and rendering',
      descriptionAr: 'تصميم وتصيير الواجهات الخارجية ثلاثية الأبعاد',
      slaDays: 6,
      slaWarningDays: 4,
      order: 9,
      dependsOnOrder: 8,
      color: '#06B6D4',
    },
    {
      phaseType: 'GREEN_BUILDING_CALC',
      phaseTypeAr: 'حسابات المباني الخضراء',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Green building calculations and compliance documentation',
      descriptionAr: 'حسابات ومستندات الامتثال للمباني الخضراء',
      slaDays: 10,
      slaWarningDays: 7,
      order: 10,
      dependsOnOrder: 9,
      color: '#16A34A',
    },
    {
      phaseType: 'BRAJEL',
      phaseTypeAr: 'مستندات البراجيل',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Barajeel documents and specifications',
      descriptionAr: 'مستندات البراجيل والمواصفات',
      slaDays: 3,
      slaWarningDays: 2,
      order: 11,
      dependsOnOrder: 10,
      color: '#A855F7',
    },
    {
      phaseType: 'FINAL_DRAWINGS',
      phaseTypeAr: 'المخططات النهائية',
      phaseCategory: 'ARCHITECTURAL',
      description: 'Final architectural construction drawings',
      descriptionAr: 'المخططات المعمارية النهائية والتنفيذية',
      slaDays: 5,
      slaWarningDays: 4,
      order: 12,
      dependsOnOrder: 11,
      color: '#10B981',
    },
  ];
}

/**
 * Create Contract Workflow Phase Template
 * Creates phases for the contract review and signing workflow.
 */
export function createContractTemplate(): WorkflowPhaseTemplateData[] {
  return [
    {
      phaseType: 'CONTRACT_REVIEW',
      phaseTypeAr: 'مراجعة العقد',
      phaseCategory: 'CONTRACTING',
      description: 'Review contract terms, conditions, and legal clauses',
      descriptionAr: 'مراجعة شروط وأحكام العقد والبنود القانونية',
      slaDays: 2,
      slaWarningDays: 1,
      order: 1,
      color: '#F59E0B',
    },
    {
      phaseType: 'CONTRACT_SIGNING',
      phaseTypeAr: 'توقيع العقد',
      phaseCategory: 'CONTRACTING',
      description: 'Contract signing by all parties',
      descriptionAr: 'توقيع العقد من جميع الأطراف',
      slaDays: 1,
      slaWarningDays: 1,
      order: 2,
      dependsOnOrder: 1,
      color: '#10B981',
    },
  ];
}

/**
 * Create Structural Workflow Phase Template
 */
export function createStructuralTemplate(): WorkflowPhaseTemplateData[] {
  return [
    {
      phaseType: 'SOIL_REPORT',
      phaseTypeAr: 'تقرير التربة',
      phaseCategory: 'STRUCTURAL',
      description: 'Soil investigation and geotechnical report',
      descriptionAr: 'تقرير التحقيق الجيوتقني وتربة الموقع',
      slaDays: 5,
      slaWarningDays: 4,
      order: 1,
      color: '#92400E',
    },
    {
      phaseType: 'FOUNDATION',
      phaseTypeAr: 'القواعد',
      phaseCategory: 'STRUCTURAL',
      description: 'Foundation design and details',
      descriptionAr: 'تصميم وتفاصيل القواعد',
      slaDays: 4,
      slaWarningDays: 3,
      order: 2,
      dependsOnOrder: 1,
      color: '#B45309',
    },
    {
      phaseType: 'BEAMS',
      phaseTypeAr: 'الكمرات',
      phaseCategory: 'STRUCTURAL',
      description: 'Beam design and reinforcement details',
      descriptionAr: 'تصميم الكمرات وتفاصيل التسليح',
      slaDays: 3,
      slaWarningDays: 2,
      order: 3,
      dependsOnOrder: 2,
      color: '#D97706',
    },
    {
      phaseType: 'COLUMNS',
      phaseTypeAr: 'الأعمدة',
      phaseCategory: 'STRUCTURAL',
      description: 'Column design and reinforcement details',
      descriptionAr: 'تصميم الأعمدة وتفاصيل التسليح',
      slaDays: 3,
      slaWarningDays: 2,
      order: 4,
      dependsOnOrder: 3,
      color: '#F59E0B',
    },
    {
      phaseType: 'SLABS',
      phaseTypeAr: 'البلاطات',
      phaseCategory: 'STRUCTURAL',
      description: 'Slab design and reinforcement details',
      descriptionAr: 'تصميم البلاطات وتفاصيل التسليح',
      slaDays: 2,
      slaWarningDays: 1,
      order: 5,
      dependsOnOrder: 4,
      color: '#FBBF24',
    },
    {
      phaseType: 'STRUCTURAL_DETAILS',
      phaseTypeAr: 'تفاصيل التصميم الإنشائي',
      phaseCategory: 'STRUCTURAL',
      description: 'Detailed structural design for columns, beams, and slabs',
      descriptionAr: 'التصميم الإنشائي التفصيلي للأعمدة والكمرات والبلاطات',
      slaDays: 3,
      slaWarningDays: 2,
      order: 6,
      dependsOnOrder: 5,
      color: '#CA8A04',
    },
    {
      phaseType: 'GREEN_BUILDING_CHECK_STR',
      phaseTypeAr: 'قائمة التحقق الخضراء',
      phaseCategory: 'STRUCTURAL',
      description: 'Green building checklist for structural elements',
      descriptionAr: 'قائمة التحقق من متطلبات المباني الخضراء للعناصر الإنشائية',
      slaDays: 4,
      slaWarningDays: 3,
      order: 7,
      dependsOnOrder: 6,
      color: '#22C55E',
    },
    {
      phaseType: 'STRUCTURAL_MODELING',
      phaseTypeAr: 'نمذجة ETABS',
      phaseCategory: 'STRUCTURAL',
      description: 'ETABS structural 3D modeling and analysis',
      descriptionAr: 'نمذجة وتحليل ثلاثي الأبعاد ببرنامج ETABS',
      slaDays: 5,
      slaWarningDays: 4,
      order: 8,
      dependsOnOrder: 7,
      color: '#7C3AED',
    },
    {
      phaseType: 'STRUCTURAL_CALC',
      phaseTypeAr: 'حسابات ETABS',
      phaseCategory: 'STRUCTURAL',
      description: 'ETABS structural calculations and analysis results',
      descriptionAr: 'حسابات وتحليلات ETABS الإنشائية',
      slaDays: 4,
      slaWarningDays: 3,
      order: 9,
      dependsOnOrder: 8,
      color: '#8B5CF6',
    },
    {
      phaseType: 'STRUCTURAL_SCHEDULES',
      phaseTypeAr: 'الجداول الإنشائية',
      phaseCategory: 'STRUCTURAL',
      description: 'Structural schedules and quantity tables',
      descriptionAr: 'الجداول الإنشائية وجداول الكميات',
      slaDays: 3,
      slaWarningDays: 2,
      order: 10,
      dependsOnOrder: 9,
      color: '#A78BFA',
    },
    {
      phaseType: 'STAIRCASE',
      phaseTypeAr: 'تفاصيل الدرج',
      phaseCategory: 'STRUCTURAL',
      description: 'Staircase design and structural details',
      descriptionAr: 'تصميم وتفاصيل الدرج الإنشائية',
      slaDays: 3,
      slaWarningDays: 2,
      order: 11,
      dependsOnOrder: 10,
      color: '#C084FC',
    },
    {
      phaseType: 'MUN_APPROVAL_STR',
      phaseTypeAr: 'اعتماد البلدية للإنشائي',
      phaseCategory: 'STRUCTURAL',
      description: 'Municipality approval for structural drawings',
      descriptionAr: 'اعتماد البلدية للمخططات الإنشائية',
      slaDays: 10,
      slaWarningDays: 7,
      order: 12,
      dependsOnOrder: 11,
      color: '#10B981',
    },
  ];
}

/**
 * Create MEP Workflow Phase Template
 */
export function createMEPTemplate(): WorkflowPhaseTemplateData[] {
  return [
    // Electrical Sub-Group
    {
      phaseType: 'NOC',
      phaseTypeAr: 'شهادة عدم المانعة',
      phaseCategory: 'MEP',
      description: 'Obtain No Objection Certificate from authorities',
      descriptionAr: 'الحصول على شهادة عدم المانعة من الجهات المختصة',
      slaDays: 5,
      slaWarningDays: 4,
      order: 1,
      color: '#DC2626',
    },
    {
      phaseType: 'ELECTRICAL',
      phaseTypeAr: 'الأعمال الكهربائية',
      phaseCategory: 'MEP',
      description: 'Electrical power distribution design',
      descriptionAr: 'تصميم توزيع الطاقة الكهربائية',
      slaDays: 4,
      slaWarningDays: 3,
      order: 2,
      color: '#EF4444',
    },
    {
      phaseType: 'AC_CALCULATIONS',
      phaseTypeAr: 'حسابات التكييف',
      phaseCategory: 'MEP',
      description: 'HVAC load calculations and system sizing',
      descriptionAr: 'حسابات أحمال التكييف وتحديد أحجام الأنظمة',
      slaDays: 7,
      slaWarningDays: 5,
      order: 3,
      color: '#7C3AED',
    },
    {
      phaseType: 'SOLAR_HEATING',
      phaseTypeAr: 'التدفئة الشمسية',
      phaseCategory: 'MEP',
      description: 'Solar water heating system design',
      descriptionAr: 'تصميم نظام التدفئة بمياه الشمسية',
      slaDays: 1,
      slaWarningDays: 1,
      order: 4,
      color: '#F59E0B',
    },
    {
      phaseType: 'LOAD_SCHEDULE',
      phaseTypeAr: 'جدول الأحمال',
      phaseCategory: 'MEP',
      description: 'Electrical load schedule and calculations',
      descriptionAr: 'جدول الأحمال الكهربائية والحسابات',
      slaDays: 2,
      slaWarningDays: 1,
      order: 5,
      dependsOnOrder: 2,
      color: '#F97316',
    },
    {
      phaseType: 'PANEL_SCHEDULE',
      phaseTypeAr: 'جدول الوحات الكهربائية',
      phaseCategory: 'MEP',
      description: 'Panel board schedule with details',
      descriptionAr: 'جدول تفاصيل اللوحات الكهربائية',
      slaDays: 2,
      slaWarningDays: 1,
      order: 6,
      dependsOnOrder: 5,
      color: '#FB923C',
    },
    {
      phaseType: 'ELEC_SPECIFICATIONS',
      phaseTypeAr: 'المواصفات والبراجيل',
      phaseCategory: 'MEP',
      description: 'Electrical specifications and Barajeel tables',
      descriptionAr: 'المواصفات الكهربائية وجداول البراجيل',
      slaDays: 2,
      slaWarningDays: 1,
      order: 7,
      dependsOnOrder: 6,
      color: '#EA580C',
    },
    {
      phaseType: 'LIGHTING',
      phaseTypeAr: 'الإنارة',
      phaseCategory: 'MEP',
      description: 'Lighting design and layout plans',
      descriptionAr: 'تصميم ومخططات الإنارة',
      slaDays: 2,
      slaWarningDays: 1,
      order: 8,
      dependsOnOrder: 6,
      color: '#FCD34D',
    },
    // Drainage Sub-Group
    {
      phaseType: 'DRAINAGE',
      phaseTypeAr: 'الصرف الصحي',
      phaseCategory: 'MEP',
      description: 'Internal sanitary drainage design',
      descriptionAr: 'تصميم الصرف الصحي الداخلي',
      slaDays: 2,
      slaWarningDays: 1,
      order: 9,
      color: '#2563EB',
    },
    {
      phaseType: 'SITE_DRAINAGE',
      phaseTypeAr: 'صرف الموقع العام',
      phaseCategory: 'MEP',
      description: 'External site drainage system design',
      descriptionAr: 'تصميم نظام الصرف للموقع العام',
      slaDays: 1,
      slaWarningDays: 1,
      order: 10,
      dependsOnOrder: 9,
      color: '#3B82F6',
    },
    {
      phaseType: 'RAIN_DRAINAGE',
      phaseTypeAr: 'صرف مياه الأمطار',
      phaseCategory: 'MEP',
      description: 'Rain water drainage system design',
      descriptionAr: 'تصميم نظام صرف مياه الأمطار من الأسطح',
      slaDays: 1,
      slaWarningDays: 1,
      order: 11,
      dependsOnOrder: 10,
      color: '#60A5FA',
    },
    {
      phaseType: 'TANK_DETAILS',
      phaseTypeAr: 'تفاصيل الخزان',
      phaseCategory: 'MEP',
      description: 'Water tank details and construction drawings',
      descriptionAr: 'تفاصيل ومخططات بناء الخزان',
      slaDays: 2,
      slaWarningDays: 1,
      order: 12,
      dependsOnOrder: 11,
      color: '#93C5FD',
    },
    // Water Supply Sub-Group
    {
      phaseType: 'WATER_SUPPLY',
      phaseTypeAr: 'توزيع إمدادات المياه',
      phaseCategory: 'MEP',
      description: 'Water supply distribution design',
      descriptionAr: 'تصميم توزيع إمدادات المياه',
      slaDays: 2,
      slaWarningDays: 1,
      order: 13,
      color: '#0891B2',
    },
    {
      phaseType: 'SITE_WATER',
      phaseTypeAr: 'مياه الموقع العام',
      phaseCategory: 'MEP',
      description: 'External site water supply design',
      descriptionAr: 'تصميم إمدادات المياه للموقع العام',
      slaDays: 1,
      slaWarningDays: 1,
      order: 14,
      dependsOnOrder: 13,
      color: '#06B6D4',
    },
    {
      phaseType: 'GROUND_FLOOR_WATER',
      phaseTypeAr: 'مياه الدور الأرضي',
      phaseCategory: 'MEP',
      description: 'Ground floor water supply distribution',
      descriptionAr: 'توزيع المياه للدور الأرضي',
      slaDays: 1,
      slaWarningDays: 1,
      order: 15,
      dependsOnOrder: 14,
      color: '#22D3EE',
    },
    {
      phaseType: 'ROOF_WATER',
      phaseTypeAr: 'مياه طابق السطح',
      phaseCategory: 'MEP',
      description: 'Roof level water supply distribution',
      descriptionAr: 'توزيع المياه لطابق السطح',
      slaDays: 1,
      slaWarningDays: 1,
      order: 16,
      dependsOnOrder: 15,
      color: '#67E8F9',
    },
    // Etisalat Sub-Group
    {
      phaseType: 'ETISALAT',
      phaseTypeAr: 'اتصالات الموقع العام',
      phaseCategory: 'MEP',
      description: 'Etisalat telecom design for general site',
      descriptionAr: 'تصميم الاتصالات للموقع العام',
      slaDays: 2,
      slaWarningDays: 1,
      order: 17,
      color: '#059669',
    },
    {
      phaseType: 'ETISALAT_GF',
      phaseTypeAr: 'اتصالات الدور الأرضي',
      phaseCategory: 'MEP',
      description: 'Etisalat telecom design for ground floor',
      descriptionAr: 'تصميم الاتصالات للدور الأرضي',
      slaDays: 1,
      slaWarningDays: 1,
      order: 18,
      dependsOnOrder: 17,
      color: '#10B981',
    },
    // HVAC
    {
      phaseType: 'HVAC',
      phaseTypeAr: 'التكييف',
      phaseCategory: 'MEP',
      description: 'HVAC ducting and system layout design',
      descriptionAr: 'تصميم تمديدات ومخططات نظام التكييف',
      slaDays: 5,
      slaWarningDays: 4,
      order: 19,
      dependsOnOrder: 3,
      color: '#7C3AED',
    },
    // Civil Defense Sub-Group
    {
      phaseType: 'CD_FIRE_SYSTEM',
      phaseTypeAr: 'نظام الحريق - الموقع',
      phaseCategory: 'MEP',
      description: 'Fire alarm and suppression system for general site',
      descriptionAr: 'نظام إنذار وإطفاء الحريق للموقع العام',
      slaDays: 2,
      slaWarningDays: 1,
      order: 20,
      color: '#DC2626',
    },
    {
      phaseType: 'CD_EMERGENCY_LIGHTING',
      phaseTypeAr: 'الإضاءة الطارئة',
      phaseCategory: 'MEP',
      description: 'Emergency lighting system design',
      descriptionAr: 'تصميم نظام الإضاءة الطارئة',
      slaDays: 2,
      slaWarningDays: 1,
      order: 21,
      color: '#EF4444',
    },
    {
      phaseType: 'CD_FIRE_FITTING',
      phaseTypeAr: 'نظام إطفاء الحريق',
      phaseCategory: 'MEP',
      description: 'Fire fighting system design and details',
      descriptionAr: 'تصميم وتفاصيل نظام إطفاء الحريق',
      slaDays: 1,
      slaWarningDays: 1,
      order: 22,
      dependsOnOrder: 20,
      color: '#B91C1C',
    },
    {
      phaseType: 'CD_SCHEMATIC',
      phaseTypeAr: 'المخطط التخطيطي',
      phaseCategory: 'MEP',
      description: 'Fire protection schematic diagram',
      descriptionAr: 'المخطط التخطيطي لنظام الحماية من الحرائق',
      slaDays: 1,
      slaWarningDays: 1,
      order: 23,
      dependsOnOrder: 22,
      color: '#991B1B',
    },
    {
      phaseType: 'MEP_COORDINATION',
      phaseTypeAr: 'تنسيق MEP',
      phaseCategory: 'MEP',
      description: 'Final MEP coordination and clash detection',
      descriptionAr: 'التنسيق النهائي وكشف التعارضات بين تخصصات MEP',
      slaDays: 3,
      slaWarningDays: 2,
      order: 24,
      dependsOnOrder: 19,
      color: '#0891B2',
    },
  ];
}

/**
 * Create Government Approvals Workflow Phase Template
 */
export function createGovernmentTemplate(): WorkflowPhaseTemplateData[] {
  return [
    {
      phaseType: 'COLLECT_DOCUMENTS',
      phaseTypeAr: 'جمع المستندات',
      phaseCategory: 'GOVERNMENT',
      description: 'Collect all required documents for government submission',
      descriptionAr: 'جمع جميع المستندات المطلوبة للتقديم الحكومي',
      slaDays: 6,
      slaWarningDays: 4,
      order: 1,
      color: '#7C3AED',
    },
    {
      phaseType: 'RENEW_KROKY',
      phaseTypeAr: 'تجديد الكروكي وفتح الملف',
      phaseCategory: 'GOVERNMENT',
      description: 'Renew Kuroky, investigation, and open file at Sheikh Zayed',
      descriptionAr: 'تجديد الكروكي والتحقيق وفتح ملف في الشيخ زايد',
      slaDays: 3,
      slaWarningDays: 2,
      order: 2,
      dependsOnOrder: 1,
      color: '#6D28D9',
    },
    {
      phaseType: 'CREATE_CASE',
      phaseTypeAr: 'إنشاء المعاملة',
      phaseCategory: 'GOVERNMENT',
      description: 'Create the government submission case (2 hours)',
      descriptionAr: 'إنشاء المعاملة الحكومية (ساعتين)',
      slaDays: 0,
      slaWarningDays: 0,
      order: 3,
      dependsOnOrder: 2,
      color: '#5B21B6',
    },
    {
      phaseType: 'MUN_SUBMISSION',
      phaseTypeAr: 'تقديم المخططات للبلدية',
      phaseCategory: 'GOVERNMENT',
      description: 'Submit drawings to municipality for review',
      descriptionAr: 'تقديم المخططات للبلدية للمراجعة',
      slaDays: 1,
      slaWarningDays: 1,
      order: 4,
      dependsOnOrder: 3,
      color: '#4C1D95',
    },
    {
      phaseType: 'SUBMIT_REJECTED',
      phaseTypeAr: 'إعادة تقديم المخططات المرفوضة',
      phaseCategory: 'GOVERNMENT',
      description: 'Resubmit rejected drawings with modifications',
      descriptionAr: 'إعادة تقديم المخططات المرفوضة بعد التعديل',
      slaDays: 5,
      slaWarningDays: 3,
      order: 5,
      color: '#DC2626',
    },
    {
      phaseType: 'ARCH_STRC_APPROVAL',
      phaseTypeAr: 'اعتماد معماري وإنشائي',
      phaseCategory: 'GOVERNMENT',
      description: 'Municipality approval for architectural and structural drawings',
      descriptionAr: 'اعتماد البلدية للمخططات المعمارية والإنشائية',
      slaDays: 10,
      slaWarningDays: 7,
      order: 6,
      dependsOnOrder: 4,
      color: '#2563EB',
    },
    {
      phaseType: 'SUBMIT_ELE_UTILITIES',
      phaseTypeAr: 'تقديم كهرباء واتصالات وصرف',
      phaseCategory: 'GOVERNMENT',
      description: 'Submit electrical, telecom, and drainage for approval',
      descriptionAr: 'تقديم الكهرباء والاتصالات والصرف للاعتماد',
      slaDays: 3,
      slaWarningDays: 2,
      order: 7,
      dependsOnOrder: 6,
      color: '#7C3AED',
    },
    {
      phaseType: 'DEMARCATION',
      phaseTypeAr: 'التحديد والتسوية',
      phaseCategory: 'GOVERNMENT',
      description: 'Site demarcation and leveling survey (2 hours)',
      descriptionAr: 'تحديد الموقع ومسح التسوية (ساعتين)',
      slaDays: 0,
      slaWarningDays: 0,
      order: 8,
      dependsOnOrder: 7,
      color: '#0891B2',
    },
    {
      phaseType: 'FINAL_PERMIT',
      phaseTypeAr: 'إصدار الرخصة النهائية',
      phaseCategory: 'GOVERNMENT',
      description: 'Issue final building permit',
      descriptionAr: 'إصدار رخصة البناء النهائية',
      slaDays: 2,
      slaWarningDays: 1,
      order: 9,
      dependsOnOrder: 8,
      color: '#10B981',
    },
    {
      phaseType: 'GET_PERMIT_FEE',
      phaseTypeAr: 'استخراج إيصال الرخصة',
      phaseCategory: 'GOVERNMENT',
      description: 'Obtain permit fee receipt',
      descriptionAr: 'استخراج إيصال رسوم الرخصة',
      slaDays: 1,
      slaWarningDays: 1,
      order: 10,
      dependsOnOrder: 9,
      color: '#F59E0B',
    },
  ];
}

