import {
  Sparkles,
  AlertTriangle,
  TrendingUp,
  Shield,
  Users,
  Calculator,
  HardHat,
  DollarSign,
  Bell,
  Lightbulb,
} from "lucide-react";

export const quickSuggestions = [
  {
    icon: Calculator,
    ar: "كيف أضع ميزانية مشروع؟",
    en: "How to set project budget?",
    arMsg: "كيف أضع ميزانية مشروع إنشائي بشكل احترافي؟",
    enMsg: "How do I set a professional budget for a construction project?",
  },
  {
    icon: AlertTriangle,
    ar: "ما هي مخاطر التأخير؟",
    en: "What are delay risks?",
    arMsg: "ما هي أبرز مخاطر التأخير في المشاريع الإنشائية وكيف أتعامل معها؟",
    enMsg: "What are the main delay risks in construction projects and how to handle them?",
  },
  {
    icon: HardHat,
    ar: "كيف أكتب تقرير موقع؟",
    en: "How to write a site report?",
    arMsg: "كيف أكتب تقرير زيارة موقع احترافي يشمل جميع التفاصيل المطلوبة؟",
    enMsg: "How do I write a professional site visit report with all required details?",
  },
  {
    icon: Users,
    ar: "نصائح لإدارة الفريق",
    en: "Team management tips",
    arMsg: "أعطني نصائح عملية لإدارة فريق هندسي في مكتب استشارات؟",
    enMsg: "Give me practical tips for managing an engineering team in a consultancy office?",
  },
  {
    icon: TrendingUp,
    ar: "حساب تكلفة البناء",
    en: "Construction cost estimate",
    arMsg: "ما هي الطرق المعتمدة لحساب تكلفة البناء في الإمارات؟",
    enMsg: "What are the standard methods for calculating construction costs in the UAE?",
  },
  {
    icon: Shield,
    ar: "شروط بلدية دبي",
    en: "Dubai Municipality rules",
    arMsg: "ما هي المتطلبات الأساسية للحصول على ترخيص بناء من بلدية دبي؟",
    enMsg: "What are the main requirements for getting a building permit from Dubai Municipality?",
  },
];

export const quickActions = [
  {
    icon: Sparkles,
    ar: "ملخص المشاريع",
    en: "Project Summary",
    arMsg: "أعطني ملخصاً شاملاً لجميع المشاريع الحالية وحالتها",
    enMsg: "Give me a comprehensive summary of all current projects and their status",
    color: "from-teal-500 to-cyan-500",
    bgLight: "bg-teal-50 dark:bg-teal-950/30",
    iconColor: "text-teal-600 dark:text-teal-400",
  },
  {
    icon: AlertTriangle,
    ar: "المهام المتأخرة",
    en: "Overdue Tasks",
    arMsg: "ما هي المهام المتأخرة حالياً وأحتاج إلى اتخاذ إجراء فوري بشأنها؟",
    enMsg: "What tasks are currently overdue and need immediate action?",
    color: "from-amber-500 to-orange-500",
    bgLight: "bg-amber-50 dark:bg-amber-950/30",
    iconColor: "text-amber-600 dark:text-amber-400",
  },
  {
    icon: DollarSign,
    ar: "الحالة المالية",
    en: "Financial Status",
    arMsg: "أعطني تقريراً عن الحالة المالية الحالية: الإيرادات، المصروفات، الفواتير المستحقة",
    enMsg: "Give me a report on the current financial status: revenue, expenses, outstanding invoices",
    color: "from-emerald-500 to-green-500",
    bgLight: "bg-emerald-50 dark:bg-emerald-950/30",
    iconColor: "text-emerald-600 dark:text-emerald-400",
  },
  {
    icon: Bell,
    ar: "تنبيهات مهمة",
    en: "Important Alerts",
    arMsg: "ما هي التنبيهات والتحذيرات المهمة التي أحتاج لمعرفتها فوراً؟",
    enMsg: "What are the important alerts and warnings I need to know about immediately?",
    color: "from-red-500 to-rose-500",
    bgLight: "bg-red-50 dark:bg-red-950/30",
    iconColor: "text-red-600 dark:text-red-400",
  },
  {
    icon: Lightbulb,
    ar: "اقتراحات تحسين",
    en: "Improvement Suggestions",
    arMsg: "بناءً على بيانات النظام الحالية، ما هي أفضل اقتراحات التحسين لتحسين الأداء؟",
    enMsg: "Based on the current system data, what are the top improvement suggestions to enhance performance?",
    color: "from-violet-500 to-purple-500",
    bgLight: "bg-violet-50 dark:bg-violet-950/30",
    iconColor: "text-violet-600 dark:text-violet-400",
  },
];
